[workspace]
members = ["lib", "cli", "web", "gcode_converter"]

[workspace.dependencies]
anyhow = "1"
env_logger = "0"
log = "0"
serde_json = "1.0.107"
structopt = { version = "0", default-features = false }
