[workspace]
members = ["lib", "cli", "web", "gcode_converter"]

[workspace.dependencies]
anyhow = "1"
clap = { version = "4.4.18", features = ["derive"] }
env_logger = "0"
log = "0"
serde_json = "1.0.107"
